'use client';

import { Routes } from '@/routes';
import type { NestedMenuItem } from '@/types';
import {
  BookOpen,
  Calculator,
  ClipboardList,
  Dice5,
  Download,
  Gamepad2,
  Gem,
  RadioTower,
  RotateCcw,
  Sparkles,
  Swords,
  Target,
  Trophy,
} from 'lucide-react';
import { useTranslations } from 'next-intl';

export function useNavbarLinks(): NestedMenuItem[] {
  const t = useTranslations('Marketing.navbar');

  return [
    {
      title: t('codes.title'),
      href: Routes.Codes,
      external: false,
      icon: <ClipboardList className="size-4" />,
      items: [
        {
          title: 'Overview',
          description: 'All active Anime Squadron codes.',
          href: Routes.Codes,
          external: false,
          icon: <ClipboardList className="size-4" />,
        },
        {
          title: 'Redeem Guide',
          description: 'How to redeem codes and avoid stale entries.',
          href: Routes.CodesGuide,
          external: false,
          icon: <BookOpen className="size-4" />,
        },
        {
          title: 'Resource Calculator',
          description: 'Turn code rewards into a spend plan.',
          href: Routes.ResourceCalculator,
          external: false,
          icon: <Gem className="size-4" />,
        },
      ],
    },
    {
      title: t('tierList.title'),
      href: Routes.TierList,
      external: false,
      icon: <Trophy className="size-4" />,
      items: [
        {
          title: 'Overview',
          description: 'Role-first unit priority table.',
          href: Routes.TierList,
          external: false,
          icon: <Trophy className="size-4" />,
        },
        {
          title: 'Best Units Guide',
          description: 'Decision notes for high-value units.',
          href: Routes.UnitsGuide,
          external: false,
          icon: <Swords className="size-4" />,
        },
        {
          title: 'UPD 0.5 Tier Guide',
          description: 'Berserker, Falcon, Gometa, and patch context.',
          href: '/guides/update-0-5-tier-list',
          external: false,
          icon: <Sparkles className="size-4" />,
        },
        {
          title: 'Secret Units Tracker',
          description: 'Premium unit watchlist and investment timing.',
          href: Routes.SecretUnitsTracker,
          external: false,
          icon: <Target className="size-4" />,
        },
      ],
    },
    {
      title: t('units.title'),
      href: Routes.Units,
      external: false,
      icon: <Swords className="size-4" />,
      items: [
        {
          title: 'Overview',
          description: 'Role hub for carries, support, control, and economy.',
          href: Routes.Units,
          external: false,
          icon: <Swords className="size-4" />,
        },
        {
          title: 'Main Carry',
          description: 'Choose the unit that gets first serious investment.',
          href: '/units/roles/main-carry',
          external: false,
          icon: <Trophy className="size-4" />,
        },
        {
          title: 'Boss Damage',
          description: 'Patch late-wave and boss pressure.',
          href: '/units/roles/boss-damage',
          external: false,
          icon: <Target className="size-4" />,
        },
        {
          title: 'Gometa Guide',
          description: 'Core premium carry and evolution target.',
          href: '/units/gometa-ssj4',
          external: false,
          icon: <Sparkles className="size-4" />,
        },
        {
          title: 'Woo Guide',
          description: 'Banner target and late investment check.',
          href: '/units/woo-shadow',
          external: false,
          icon: <Swords className="size-4" />,
        },
        {
          title: 'Best Team Combo',
          description: 'Plan squad slots before spending rerolls.',
          href: Routes.BestTeamCombo,
          external: false,
          icon: <Calculator className="size-4" />,
        },
      ],
    },
    {
      title: t('traits.title'),
      href: Routes.Traits,
      external: false,
      icon: <Sparkles className="size-4" />,
      items: [
        {
          title: 'Overview',
          description: 'Trait priorities and keeper-unit rules.',
          href: Routes.Traits,
          external: false,
          icon: <Sparkles className="size-4" />,
        },
        {
          title: 'Traits Guide',
          description: 'Carry-first reroll planning.',
          href: Routes.TraitsGuide,
          external: false,
          icon: <BookOpen className="size-4" />,
        },
        {
          title: 'Trait Reroll Calculator',
          description: 'Estimate reported trait odds.',
          href: Routes.TraitRerollCalculator,
          external: false,
          icon: <Dice5 className="size-4" />,
        },
        {
          title: 'Shard Farm Guide',
          description: 'Plan Trait Shards and Reroll Cubes.',
          href: '/guides/trait-shards-reroll-cubes-farm',
          external: false,
          icon: <Gem className="size-4" />,
        },
      ],
    },
    {
      title: t('tools.title'),
      external: false,
      icon: <Calculator className="size-4" />,
      items: [
        {
          title: 'Best Team Combo',
          description: 'Build squad roles and slot coverage.',
          href: Routes.BestTeamCombo,
          external: false,
          icon: <Swords className="size-4" />,
        },
        {
          title: 'Resource Calculator',
          description: 'Plan Gems, Gold, cubes, and code rewards.',
          href: Routes.ResourceCalculator,
          external: false,
          icon: <Gem className="size-4" />,
        },
        {
          title: 'Trait Reroll Calculator',
          description: 'Estimate reported trait reroll odds.',
          href: Routes.TraitRerollCalculator,
          external: false,
          icon: <Dice5 className="size-4" />,
        },
        {
          title: 'Woo Pity Calculator',
          description: 'Plan banner pulls, Gems, and pity pressure.',
          href: Routes.WooPityCalculator,
          external: false,
          icon: <Target className="size-4" />,
        },
        {
          title: 'Secret Units Tracker',
          description: 'Track premium units and investment timing.',
          href: Routes.SecretUnitsTracker,
          external: false,
          icon: <Sparkles className="size-4" />,
        },
      ],
    },
    {
      title: t('reroll.title'),
      href: Routes.Reroll,
      external: false,
      icon: <RotateCcw className="size-4" />,
      items: [
        {
          title: 'Overview',
          description: 'Stat reroll and stop-rule hub.',
          href: Routes.Reroll,
          external: false,
          icon: <RotateCcw className="size-4" />,
        },
        {
          title: 'Stat Reroll Guide',
          description: 'When to reroll stats and when to stop.',
          href: Routes.RerollGuide,
          external: false,
          icon: <BookOpen className="size-4" />,
        },
        {
          title: 'Trait Reroll Calculator',
          description: 'Run probability math before spending.',
          href: Routes.TraitRerollCalculator,
          external: false,
          icon: <Dice5 className="size-4" />,
        },
        {
          title: 'Resource Calculator',
          description: 'Budget cubes, shards, rerolls, and Gems.',
          href: Routes.ResourceCalculator,
          external: false,
          icon: <Gem className="size-4" />,
        },
      ],
    },
    {
      title: t('guides.title'),
      href: Routes.Guides,
      external: false,
      icon: <BookOpen className="size-4" />,
      items: [
        {
          title: 'Overview',
          description: 'All Anime Squadron guides.',
          href: Routes.Guides,
          external: false,
          icon: <BookOpen className="size-4" />,
        },
        {
          title: 'Beginner Guide',
          description: 'First-hour route and early spending order.',
          href: Routes.BeginnerGuide,
          external: false,
          icon: <Sparkles className="size-4" />,
        },
        {
          title: 'Gems and Gold',
          description: 'Spend core currencies without wasting tempo.',
          href: '/guides/gems-gold-spending-guide',
          external: false,
          icon: <Gem className="size-4" />,
        },
        {
          title: 'Infinite Mode',
          description: 'Farm routes and late-wave planning.',
          href: '/guides/infinite-mode-farming-guide',
          external: false,
          icon: <Gamepad2 className="size-4" />,
        },
        {
          title: 'Gear Crafting',
          description: 'Craft gear after a unit has a role.',
          href: '/guides/gear-crafting-guide',
          external: false,
          icon: <Swords className="size-4" />,
        },
        {
          title: 'Discord / Trello',
          description: 'Community and official link safety.',
          href: '/guides/discord-trello-wiki-guide',
          external: false,
          icon: <RadioTower className="size-4" />,
        },
      ],
    },
    {
      title: t('gameModes.title'),
      href: Routes.GameModes,
      external: false,
      icon: <Gamepad2 className="size-4" />,
      items: [
        {
          title: 'Overview',
          description: 'Mode priorities and reward planning.',
          href: Routes.GameModes,
          external: false,
          icon: <Gamepad2 className="size-4" />,
        },
        {
          title: 'Rewards Guide',
          description: 'Match modes to Gems, Gold, and materials.',
          href: Routes.ModesGuide,
          external: false,
          icon: <BookOpen className="size-4" />,
        },
        {
          title: 'Infinite Mode',
          description: 'Late-wave farming and reroll material flow.',
          href: '/guides/infinite-mode-farming-guide',
          external: false,
          icon: <RotateCcw className="size-4" />,
        },
        {
          title: 'Team Combo',
          description: 'Check roles before pushing harder modes.',
          href: Routes.BestTeamCombo,
          external: false,
          icon: <Swords className="size-4" />,
        },
      ],
    },
    {
      title: t('discord.title'),
      href: Routes.Discord,
      external: false,
      icon: <RadioTower className="size-4" />,
    },
    {
      title: t('download.title'),
      href: Routes.Download,
      external: false,
      icon: <Download className="size-4" />,
    },
  ];
}
